apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aqja
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aqja
    app.kubernetes.io/part-of: ci1t-830-0050-app
  name: devfile-sample-aqja
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aqja
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aqja
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0050-tenant/ci1t-830-0050-app/devfile-sample-aqja@sha256:225248313f51439a177caa2f17b856c37a21142d7dafb6907d84a5b5a7580833
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
